### ISSUE TITLE
Optimized the fishing speed and added the ability for the user to change the screen region capture size in the GUI

### ISSUE THREAD

**Issue by hosua** [FairfieldTekLLC/McFishing#3]
Hello, first, thanks for the fishing bot! It works great. I made some slight improvements/changes to it, check out the fork [here!](https://github.com/hosua/McFishing)

It's not much, but the fishing bot now casts the rod after catching a fish much faster than before. I also added the ability to change the screen region capture size because I ran into issues with this and felt the need for it to be added.

**Comment by FairfieldTekLLC** [comment]
Great!

Could you give me a pull request?  I’d love to pull your code into root.

That or I can add you as a contributor to the project.

Vince Gee

From: hosua ***@***.***>
Sent: Tuesday, July 27, 2021 1:29 AM
To: FairfieldTekLLC/McFishing ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FairfieldTekLLC/McFishing] Optimized the fishing speed and added the ability for the user to change the screen region capture size in the GUI (#3)


Hello, first, thanks for the fishing bot! It works great. I made some slight improvements/changes to it, check out the fork here!<https://github.com/hosua/McFishing>

It's not much, but the fishing bot now casts the rod after catching a fish much faster than before. I also added the ability to change the screen region capture size because I ran into issues with this and felt the need for it to be added.

**Comment by hosua** [comment]
Gotcha, just sent the pull request. Let me know if I did anything wrong, it's my first one lol

**Comment by eternosikk** [comment]
Hello, I would like to ask for help with your script because when I start it, it does not work completely below I am sending a video I would ask for urgent help thanks https://youtu.be/0C3X7-KY5Eg

**Comment by FairfieldTekLLC** [comment]
Hey there,

Ok, the problem is that you need to change the screen location of where the program is looking for the bobber.
I never planned the program to be consumed by other people, just was storing it😊

So to fix it, in the code you will find there is a spot where I take the screen shot to evaluate.
Just change the XY cords to where the bobber normally is.
Also I would highly recommend that you dock Minecraft  to the right side of your monitor so it always is the same size window.
That way, once you find where the bobber normally is, it won’t change.
